name: razorpay-demo
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@321
      POSTGRES_DB: razorpay_demo
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"

volumes:
  postgres:
    driver: local
